SELECT CONCAT(DRIVERS.FORENAME, " ", DRIVERS.SURNAME) AS 'PILOTO', COUNT(RESULTS.POSITION) AS 'VITORIAS' FROM results RESULTS
INNER JOIN drivers DRIVERS
    ON DRIVERS.DRIVERID = RESULTS.DRIVERID
INNER JOIN races RACES
    ON RACES.RACEID = RESULTS.RACEID
WHERE RESULTS.POSITION = 1
GROUP BY PILOTO
ORDER BY VITORIAS DESC;