SELECT TAB_VITORIAS.* , TOTAL_CORRIDAS.NUMERO_DE_CORRIDAS ,  TAB_VITORIAS.VITORIAS/TOTAL_CORRIDAS.NUMERO_DE_CORRIDAS APROVEITAMENTO
FROM
    (SELECT CONCAT(DRIVERS.FORENAME, " ", DRIVERS.SURNAME) AS 'PILOTO', COUNT(RESULTS.POSITION) AS 'VITORIAS' FROM results RESULTS
    INNER JOIN drivers DRIVERS
        ON DRIVERS.DRIVERID = RESULTS.DRIVERID
    INNER JOIN races RACES
        ON RACES.RACEID = RESULTS.RACEID
    WHERE RESULTS.POSITION = 1
    GROUP BY PILOTO) TAB_VITORIAS
INNER JOIN 
    (SELECT CONCAT(DRIVERS.FORENAME," ",DRIVERS.SURNAME) NAME,
        COUNT(RESULTS.DRIVERID)  NUMERO_DE_CORRIDAS FROM results RESULTS
        INNER JOIN drivers DRIVERS ON RESULTS.DRIVERID = DRIVERS.DRIVERID
        GROUP BY CONCAT(DRIVERS.FORENAME," ",DRIVERS.SURNAME)) TOTAL_CORRIDAS
ON TOTAL_CORRIDAS.NAME = TAB_VITORIAS.PILOTO
WHERE VITORIAS > 5
ORDER BY VITORIAS DESC
LIMIT 30;