SELECT TAB.*
FROM
    (SELECT CIRCUITS.NAME CIRCUITO, CONCAT(DRIVERS.FORENAME, " ", DRIVERS.SURNAME) PILOTO, COUNT(RESULTS.POSITION) VITORIAS FROM results RESULTS
    INNER JOIN drivers DRIVERS
        ON DRIVERS.DRIVERID = RESULTS.DRIVERID
    INNER JOIN races RACES
        ON RACES.RACEID = RESULTS.RACEID
    INNER JOIN circuits CIRCUITS
        ON CIRCUITS.CIRCUITID = RACES.CIRCUITID
    WHERE RESULTS.POSITION = 1
    GROUP BY PILOTO, CIRCUITO) TAB
INNER JOIN
    (SELECT VCIRCUIT.CIRCUITO CIRCUITO, MAX(VCIRCUIT.VITORIAS) VITORIAS FROM
    (SELECT CIRCUITS.NAME CIRCUITO, CONCAT(DRIVERS.FORENAME, " ", DRIVERS.SURNAME) PILOTO, COUNT(RESULTS.POSITION) VITORIAS FROM results RESULTS
    INNER JOIN drivers DRIVERS
        ON DRIVERS.DRIVERID = RESULTS.DRIVERID
    INNER JOIN races RACES
        ON RACES.RACEID = RESULTS.RACEID
    INNER JOIN circuits CIRCUITS
        ON CIRCUITS.CIRCUITID = RACES.CIRCUITID
    WHERE RESULTS.POSITION = 1
    GROUP BY PILOTO, CIRCUITO
    ORDER BY VITORIAS DESC) VCIRCUIT
    GROUP BY VCIRCUIT.CIRCUITO) MAXIMO
ON TAB.CIRCUITO = MAXIMO.CIRCUITO AND MAXIMO.VITORIAS = TAB.VITORIAS
ORDER BY VITORIAS DESC;