SELECT TAB.*
FROM
    (SELECT RACES.YEAR AS 'TEMPORADA', CONCAT(DRIVERS.FORENAME, " ", DRIVERS.SURNAME) AS 'PILOTO', COUNT(RESULTS.POSITION) AS 'VITORIAS' FROM results RESULTS
    INNER JOIN drivers DRIVERS
        ON DRIVERS.DRIVERID = RESULTS.DRIVERID
    INNER JOIN races RACES
        ON RACES.RACEID = RESULTS.RACEID
    INNER JOIN circuits CIRCUITS
        ON CIRCUITS.CIRCUITID = RACES.CIRCUITID
    WHERE RESULTS.POSITION = 1
    GROUP BY PILOTO, TEMPORADA) TAB
INNER JOIN
    (SELECT V_ANO.ANO ANO, MAX(V_ANO.VITORIAS) VITORIAS FROM
        (SELECT RACES.YEAR ANO, CONCAT(DRIVERS.FORENAME, " ", DRIVERS.SURNAME) PILOTO, COUNT(RESULTS.POSITION) VITORIAS FROM results RESULTS
        INNER JOIN drivers DRIVERS
            ON DRIVERS.DRIVERID = RESULTS.DRIVERID
        INNER JOIN races RACES
            ON RACES.RACEID = RESULTS.RACEID
        WHERE RESULTS.POSITION = 1
        GROUP BY PILOTO, ANO
        ORDER BY VITORIAS DESC) V_ANO
        GROUP BY V_ANO.ANO) MAXIMO
ON MAXIMO.VITORIAS = TAB.VITORIAS AND MAXIMO.ANO = TAB.TEMPORADA
ORDER BY TEMPORADA DESC;