SELECT VCIRCUIT.CIRCUITO AS 'CIRCUITO', MAX(VCIRCUIT.VITORIAS) AS 'VITORIAS' FROM
(SELECT CIRCUITS.NAME AS 'CIRCUITO', CONCAT(DRIVERS.FORENAME, " ", DRIVERS.SURNAME) AS 'PILOTO', COUNT(RESULTS.POSITION) AS 'VITORIAS' FROM results RESULTS
INNER JOIN drivers DRIVERS
    ON DRIVERS.DRIVERID = RESULTS.DRIVERID
INNER JOIN races RACES
    ON RACES.RACEID = RESULTS.RACEID
INNER JOIN circuits CIRCUITS
    ON CIRCUITS.CIRCUITID = RACES.CIRCUITID
WHERE RESULTS.POSITION = 1
GROUP BY PILOTO, CIRCUITO
ORDER BY VITORIAS DESC) VCIRCUIT
GROUP BY VCIRCUIT.CIRCUITO;