GROUP BY PILOTO, TEMPORADA;
SELECT CONCAT(DRIVERS.FORENAME, " ", DRIVERS.SURNAME) AS 'PILOTO', MIN(PITSTOPS.MILLISECONDS) AS "PITSTOP", RACES.YEAR AS 'TEMPORADA' FROM results RESULTS
INNER JOIN drivers DRIVERS
    ON DRIVERS.DRIVERID = RESULTS.DRIVERID
INNER JOIN races RACES
    ON RACES.RACEID = RESULTS.RACEID
INNER JOIN pitStops PITSTOPS
    ON PITSTOPS.RACEID = RESULTS.RACEID;