SELECT CONCAT(DRIVERS.FORENAME, " ", DRIVERS.SURNAME) AS 'PILOTO', MIN(PITSTOPS.MILLISECONDS) AS "PITSTOP" FROM results RESULTS
INNER JOIN drivers DRIVERS
    ON DRIVERS.DRIVERID = RESULTS.DRIVERID
INNER JOIN races RACES
    ON RACES.RACEID = RESULTS.RACEID
INNER JOIN pitStops PITSTOPS
    ON RESULTS.RACEID = PITSTOPS.RACEID
GROUP BY PILOTO
ORDER BY PITSTOP ASC;