SELECT CONCAT(CGRID.SURNAME," ", CGRID.FORENAME) PILOTO, CGRID.POLE POLE, (CGRID.POLE/TOT.TOTAL*100) PERCENT
FROM
(SELECT D.SURNAME, D.FORENAME, COUNT(R.GRID) POLE
FROM results R 
INNER JOIN  drivers D ON R.DRIVERID = D.DRIVERID 
WHERE GRID = 1 GROUP BY D.SURNAME, D.FORENAME ORDER BY COUNT(GRID) DESC) CGRID
INNER JOIN
(SELECT D.SURNAME, D.FORENAME, COUNT(R.DRIVERID) TOTAL
FROM results R 
INNER JOIN drivers D ON R.DRIVERID = D.DRIVERID
GROUP BY D.SURNAME, D.FORENAME) TOT
ON TOT.SURNAME = CGRID.SURNAME AND TOT.FORENAME = CGRID.FORENAME
WHERE POLE > 5
ORDER BY PERCENT DESC;