SELECT TT_PONTOS.NAME AS NAME, TT_PONTOS.TOTAL_DE_PONTOS AS TOTAL_PONTOS, P_PADRAO.PONTOS_PADRONIZADOS AS PONTOS_PADRONIZADOS, 
TT_PONTOS.NUMERO_DE_CORRIDAS AS NUMERO_CORRIDAS, (P_PADRAO.PONTOS_PADRONIZADOS/TT_PONTOS.NUMERO_DE_CORRIDAS) AS PONTOS_PADRONIZADOS_POR_CORRIDA
FROM
    (SELECT CONCAT(DRIVERS.FORENAME," ",DRIVERS.SURNAME) NAME, SUM(RESULTS.POINTS) AS TOTAL_DE_PONTOS,
    COUNT(RESULTS.DRIVERID) AS NUMERO_DE_CORRIDAS FROM results RESULTS
    INNER JOIN drivers DRIVERS ON RESULTS.DRIVERID = DRIVERS.DRIVERID
    GROUP BY CONCAT(DRIVERS.FORENAME," ",DRIVERS.SURNAME)) TT_PONTOS
INNER JOIN 
    (SELECT PP.NAME, SUM(PP.PONTOS_PADRONIZADOS) AS PONTOS_PADRONIZADOS
    FROM
        (SELECT CONCAT(DRIVERS.FORENAME," ",DRIVERS.SURNAME) NAME, 
        CASE 
            WHEN RESULTS.POSITION = 1 THEN 10
            WHEN RESULTS.POSITION = 2 THEN 6 
            WHEN RESULTS.POSITION = 3 THEN 4 
            WHEN RESULTS.POSITION = 4 THEN 3 
            WHEN RESULTS.POSITION = 5 THEN 2 
            WHEN RESULTS.POSITION = 6 THEN 1
        ELSE 0
        END AS PONTOS_PADRONIZADOS
        FROM results RESULTS
        INNER JOIN drivers DRIVERS ON RESULTS.DRIVERID = DRIVERS.DRIVERID) PP
    GROUP BY PP.NAME) P_PADRAO
ON P_PADRAO.NAME = TT_PONTOS.NAME
ORDER BY P_PADRAO.PONTOS_PADRONIZADOS DESC;