SELECT CONCAT(CGRID.FORENAME," ",CGRID.SURNAME) NAME, CGRID.PODIUM, ROUND(CGRID.PODIUM/TOTAL_CORRIDAS.TOTAL*100,2) PERCENT, TOTAL_CORRIDAS.TOTAL
FROM
    (SELECT DRIVERS.SURNAME, DRIVERS.FORENAME, COUNT(RESULTS.POSITION) PODIUM
    FROM results RESULTS 
    INNER JOIN  drivers DRIVERS ON RESULTS.DRIVERID = DRIVERS.DRIVERID 
    WHERE RESULTS.POSITION IN (1,2,3)
    GROUP BY DRIVERS.SURNAME, DRIVERS.FORENAME ) CGRID
INNER JOIN
    (SELECT DRIVERS.SURNAME, DRIVERS.FORENAME, COUNT(RESULTS.DRIVERID) TOTAL
    FROM results RESULTS 
    INNER JOIN drivers DRIVERS ON RESULTS.DRIVERID = DRIVERS.DRIVERID
    GROUP BY DRIVERS.SURNAME, DRIVERS.FORENAME) TOTAL_CORRIDAS
ON TOTAL_CORRIDAS.SURNAME = CGRID.SURNAME AND TOTAL_CORRIDAS.FORENAME = CGRID.FORENAME
WHERE PODIUM > 10
ORDER BY PERCENT DESC; 